//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.Web.PassagemWs {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Passagem", Namespace="http://tom.org/")]
    [System.SerializableAttribute()]
    public partial class Passagem : TOM.Web.PassagemWs.BaseEntityOfPassagem {
        
        private decimal ValorPassagemField;
        
        private System.DateTime DataVooField;
        
        private int IdVooField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TOM.Web.PassagemWs.Voo VooField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal ValorPassagem {
            get {
                return this.ValorPassagemField;
            }
            set {
                if ((this.ValorPassagemField.Equals(value) != true)) {
                    this.ValorPassagemField = value;
                    this.RaisePropertyChanged("ValorPassagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime DataVoo {
            get {
                return this.DataVooField;
            }
            set {
                if ((this.DataVooField.Equals(value) != true)) {
                    this.DataVooField = value;
                    this.RaisePropertyChanged("DataVoo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int IdVoo {
            get {
                return this.IdVooField;
            }
            set {
                if ((this.IdVooField.Equals(value) != true)) {
                    this.IdVooField = value;
                    this.RaisePropertyChanged("IdVoo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public TOM.Web.PassagemWs.Voo Voo {
            get {
                return this.VooField;
            }
            set {
                if ((object.ReferenceEquals(this.VooField, value) != true)) {
                    this.VooField = value;
                    this.RaisePropertyChanged("Voo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntityOfPassagem", Namespace="http://tom.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TOM.Web.PassagemWs.Passagem))]
    public partial class BaseEntityOfPassagem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Voo", Namespace="http://tom.org/")]
    [System.SerializableAttribute()]
    public partial class Voo : TOM.Web.PassagemWs.BaseEntityOfVoo {
        
        private System.DateTime DataVooField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrigemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AeronaveField;
        
        private int NumeroVooField;
        
        private int QuantidadeAssentosField;
        
        private decimal ValorUnicoPassagemField;
        
        private System.Nullable<int> QuantidadeAssentosLivresField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime DataVoo {
            get {
                return this.DataVooField;
            }
            set {
                if ((this.DataVooField.Equals(value) != true)) {
                    this.DataVooField = value;
                    this.RaisePropertyChanged("DataVoo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Origem {
            get {
                return this.OrigemField;
            }
            set {
                if ((object.ReferenceEquals(this.OrigemField, value) != true)) {
                    this.OrigemField = value;
                    this.RaisePropertyChanged("Origem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Destino {
            get {
                return this.DestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinoField, value) != true)) {
                    this.DestinoField = value;
                    this.RaisePropertyChanged("Destino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Aeronave {
            get {
                return this.AeronaveField;
            }
            set {
                if ((object.ReferenceEquals(this.AeronaveField, value) != true)) {
                    this.AeronaveField = value;
                    this.RaisePropertyChanged("Aeronave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int NumeroVoo {
            get {
                return this.NumeroVooField;
            }
            set {
                if ((this.NumeroVooField.Equals(value) != true)) {
                    this.NumeroVooField = value;
                    this.RaisePropertyChanged("NumeroVoo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int QuantidadeAssentos {
            get {
                return this.QuantidadeAssentosField;
            }
            set {
                if ((this.QuantidadeAssentosField.Equals(value) != true)) {
                    this.QuantidadeAssentosField = value;
                    this.RaisePropertyChanged("QuantidadeAssentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal ValorUnicoPassagem {
            get {
                return this.ValorUnicoPassagemField;
            }
            set {
                if ((this.ValorUnicoPassagemField.Equals(value) != true)) {
                    this.ValorUnicoPassagemField = value;
                    this.RaisePropertyChanged("ValorUnicoPassagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> QuantidadeAssentosLivres {
            get {
                return this.QuantidadeAssentosLivresField;
            }
            set {
                if ((this.QuantidadeAssentosLivresField.Equals(value) != true)) {
                    this.QuantidadeAssentosLivresField = value;
                    this.RaisePropertyChanged("QuantidadeAssentosLivres");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntityOfVoo", Namespace="http://tom.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TOM.Web.PassagemWs.Voo))]
    public partial class BaseEntityOfVoo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tom.org/", ConfigurationName="PassagemWs.PassagemWSSoap")]
    public interface PassagemWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tom.org/ComprarBilhete", ReplyAction="*")]
        bool ComprarBilhete(int idVoo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tom.org/ComprarBilhete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ComprarBilheteAsync(int idVoo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tom.org/ComprarBilhetes", ReplyAction="*")]
        bool ComprarBilhetes(int numeroVoo, int quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tom.org/ComprarBilhetes", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ComprarBilhetesAsync(int numeroVoo, int quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tom.org/DevolverBilhete", ReplyAction="*")]
        bool DevolverBilhete(int numeroVoo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tom.org/DevolverBilhete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DevolverBilheteAsync(int numeroVoo);
        
        // CODEGEN: Generating message contract since element name BuscarTodasResult from namespace http://tom.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tom.org/BuscarTodas", ReplyAction="*")]
        TOM.Web.PassagemWs.BuscarTodasResponse BuscarTodas(TOM.Web.PassagemWs.BuscarTodasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tom.org/BuscarTodas", ReplyAction="*")]
        System.Threading.Tasks.Task<TOM.Web.PassagemWs.BuscarTodasResponse> BuscarTodasAsync(TOM.Web.PassagemWs.BuscarTodasRequest request);
        
        // CODEGEN: Generating message contract since element name BuscarPorVooResult from namespace http://tom.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tom.org/BuscarPorVoo", ReplyAction="*")]
        TOM.Web.PassagemWs.BuscarPorVooResponse BuscarPorVoo(TOM.Web.PassagemWs.BuscarPorVooRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tom.org/BuscarPorVoo", ReplyAction="*")]
        System.Threading.Tasks.Task<TOM.Web.PassagemWs.BuscarPorVooResponse> BuscarPorVooAsync(TOM.Web.PassagemWs.BuscarPorVooRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarTodasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarTodas", Namespace="http://tom.org/", Order=0)]
        public TOM.Web.PassagemWs.BuscarTodasRequestBody Body;
        
        public BuscarTodasRequest() {
        }
        
        public BuscarTodasRequest(TOM.Web.PassagemWs.BuscarTodasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class BuscarTodasRequestBody {
        
        public BuscarTodasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarTodasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarTodasResponse", Namespace="http://tom.org/", Order=0)]
        public TOM.Web.PassagemWs.BuscarTodasResponseBody Body;
        
        public BuscarTodasResponse() {
        }
        
        public BuscarTodasResponse(TOM.Web.PassagemWs.BuscarTodasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tom.org/")]
    public partial class BuscarTodasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TOM.Web.PassagemWs.Passagem[] BuscarTodasResult;
        
        public BuscarTodasResponseBody() {
        }
        
        public BuscarTodasResponseBody(TOM.Web.PassagemWs.Passagem[] BuscarTodasResult) {
            this.BuscarTodasResult = BuscarTodasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarPorVooRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarPorVoo", Namespace="http://tom.org/", Order=0)]
        public TOM.Web.PassagemWs.BuscarPorVooRequestBody Body;
        
        public BuscarPorVooRequest() {
        }
        
        public BuscarPorVooRequest(TOM.Web.PassagemWs.BuscarPorVooRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tom.org/")]
    public partial class BuscarPorVooRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idVoo;
        
        public BuscarPorVooRequestBody() {
        }
        
        public BuscarPorVooRequestBody(int idVoo) {
            this.idVoo = idVoo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarPorVooResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarPorVooResponse", Namespace="http://tom.org/", Order=0)]
        public TOM.Web.PassagemWs.BuscarPorVooResponseBody Body;
        
        public BuscarPorVooResponse() {
        }
        
        public BuscarPorVooResponse(TOM.Web.PassagemWs.BuscarPorVooResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tom.org/")]
    public partial class BuscarPorVooResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TOM.Web.PassagemWs.Passagem[] BuscarPorVooResult;
        
        public BuscarPorVooResponseBody() {
        }
        
        public BuscarPorVooResponseBody(TOM.Web.PassagemWs.Passagem[] BuscarPorVooResult) {
            this.BuscarPorVooResult = BuscarPorVooResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PassagemWSSoapChannel : TOM.Web.PassagemWs.PassagemWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PassagemWSSoapClient : System.ServiceModel.ClientBase<TOM.Web.PassagemWs.PassagemWSSoap>, TOM.Web.PassagemWs.PassagemWSSoap {
        
        public PassagemWSSoapClient() {
        }
        
        public PassagemWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PassagemWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PassagemWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PassagemWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ComprarBilhete(int idVoo) {
            return base.Channel.ComprarBilhete(idVoo);
        }
        
        public System.Threading.Tasks.Task<bool> ComprarBilheteAsync(int idVoo) {
            return base.Channel.ComprarBilheteAsync(idVoo);
        }
        
        public bool ComprarBilhetes(int numeroVoo, int quantidade) {
            return base.Channel.ComprarBilhetes(numeroVoo, quantidade);
        }
        
        public System.Threading.Tasks.Task<bool> ComprarBilhetesAsync(int numeroVoo, int quantidade) {
            return base.Channel.ComprarBilhetesAsync(numeroVoo, quantidade);
        }
        
        public bool DevolverBilhete(int numeroVoo) {
            return base.Channel.DevolverBilhete(numeroVoo);
        }
        
        public System.Threading.Tasks.Task<bool> DevolverBilheteAsync(int numeroVoo) {
            return base.Channel.DevolverBilheteAsync(numeroVoo);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TOM.Web.PassagemWs.BuscarTodasResponse TOM.Web.PassagemWs.PassagemWSSoap.BuscarTodas(TOM.Web.PassagemWs.BuscarTodasRequest request) {
            return base.Channel.BuscarTodas(request);
        }
        
        public TOM.Web.PassagemWs.Passagem[] BuscarTodas() {
            TOM.Web.PassagemWs.BuscarTodasRequest inValue = new TOM.Web.PassagemWs.BuscarTodasRequest();
            inValue.Body = new TOM.Web.PassagemWs.BuscarTodasRequestBody();
            TOM.Web.PassagemWs.BuscarTodasResponse retVal = ((TOM.Web.PassagemWs.PassagemWSSoap)(this)).BuscarTodas(inValue);
            return retVal.Body.BuscarTodasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TOM.Web.PassagemWs.BuscarTodasResponse> TOM.Web.PassagemWs.PassagemWSSoap.BuscarTodasAsync(TOM.Web.PassagemWs.BuscarTodasRequest request) {
            return base.Channel.BuscarTodasAsync(request);
        }
        
        public System.Threading.Tasks.Task<TOM.Web.PassagemWs.BuscarTodasResponse> BuscarTodasAsync() {
            TOM.Web.PassagemWs.BuscarTodasRequest inValue = new TOM.Web.PassagemWs.BuscarTodasRequest();
            inValue.Body = new TOM.Web.PassagemWs.BuscarTodasRequestBody();
            return ((TOM.Web.PassagemWs.PassagemWSSoap)(this)).BuscarTodasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TOM.Web.PassagemWs.BuscarPorVooResponse TOM.Web.PassagemWs.PassagemWSSoap.BuscarPorVoo(TOM.Web.PassagemWs.BuscarPorVooRequest request) {
            return base.Channel.BuscarPorVoo(request);
        }
        
        public TOM.Web.PassagemWs.Passagem[] BuscarPorVoo(int idVoo) {
            TOM.Web.PassagemWs.BuscarPorVooRequest inValue = new TOM.Web.PassagemWs.BuscarPorVooRequest();
            inValue.Body = new TOM.Web.PassagemWs.BuscarPorVooRequestBody();
            inValue.Body.idVoo = idVoo;
            TOM.Web.PassagemWs.BuscarPorVooResponse retVal = ((TOM.Web.PassagemWs.PassagemWSSoap)(this)).BuscarPorVoo(inValue);
            return retVal.Body.BuscarPorVooResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TOM.Web.PassagemWs.BuscarPorVooResponse> TOM.Web.PassagemWs.PassagemWSSoap.BuscarPorVooAsync(TOM.Web.PassagemWs.BuscarPorVooRequest request) {
            return base.Channel.BuscarPorVooAsync(request);
        }
        
        public System.Threading.Tasks.Task<TOM.Web.PassagemWs.BuscarPorVooResponse> BuscarPorVooAsync(int idVoo) {
            TOM.Web.PassagemWs.BuscarPorVooRequest inValue = new TOM.Web.PassagemWs.BuscarPorVooRequest();
            inValue.Body = new TOM.Web.PassagemWs.BuscarPorVooRequestBody();
            inValue.Body.idVoo = idVoo;
            return ((TOM.Web.PassagemWs.PassagemWSSoap)(this)).BuscarPorVooAsync(inValue);
        }
    }
}
