//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.Web.VooWs {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntityOfVoo", Namespace="http://tom.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TOM.Web.VooWs.Voo))]
    public partial class BaseEntityOfVoo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Voo", Namespace="http://tom.org/")]
    [System.SerializableAttribute()]
    public partial class Voo : TOM.Web.VooWs.BaseEntityOfVoo {
        
        private System.DateTime DataVooField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrigemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AeronaveField;
        
        private int NumeroVooField;
        
        private int QuantidadeAssentosField;
        
        private decimal ValorUnicoPassagemField;
        
        private System.Nullable<int> QuantidadeAssentosLivresField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime DataVoo {
            get {
                return this.DataVooField;
            }
            set {
                if ((this.DataVooField.Equals(value) != true)) {
                    this.DataVooField = value;
                    this.RaisePropertyChanged("DataVoo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Origem {
            get {
                return this.OrigemField;
            }
            set {
                if ((object.ReferenceEquals(this.OrigemField, value) != true)) {
                    this.OrigemField = value;
                    this.RaisePropertyChanged("Origem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Destino {
            get {
                return this.DestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinoField, value) != true)) {
                    this.DestinoField = value;
                    this.RaisePropertyChanged("Destino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Aeronave {
            get {
                return this.AeronaveField;
            }
            set {
                if ((object.ReferenceEquals(this.AeronaveField, value) != true)) {
                    this.AeronaveField = value;
                    this.RaisePropertyChanged("Aeronave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int NumeroVoo {
            get {
                return this.NumeroVooField;
            }
            set {
                if ((this.NumeroVooField.Equals(value) != true)) {
                    this.NumeroVooField = value;
                    this.RaisePropertyChanged("NumeroVoo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int QuantidadeAssentos {
            get {
                return this.QuantidadeAssentosField;
            }
            set {
                if ((this.QuantidadeAssentosField.Equals(value) != true)) {
                    this.QuantidadeAssentosField = value;
                    this.RaisePropertyChanged("QuantidadeAssentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal ValorUnicoPassagem {
            get {
                return this.ValorUnicoPassagemField;
            }
            set {
                if ((this.ValorUnicoPassagemField.Equals(value) != true)) {
                    this.ValorUnicoPassagemField = value;
                    this.RaisePropertyChanged("ValorUnicoPassagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> QuantidadeAssentosLivres {
            get {
                return this.QuantidadeAssentosLivresField;
            }
            set {
                if ((this.QuantidadeAssentosLivresField.Equals(value) != true)) {
                    this.QuantidadeAssentosLivresField = value;
                    this.RaisePropertyChanged("QuantidadeAssentosLivres");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FiltroBuscaVooDTO", Namespace="http://tom.org/")]
    [System.SerializableAttribute()]
    public partial class FiltroBuscaVooDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataVooField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrigemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DataVoo {
            get {
                return this.DataVooField;
            }
            set {
                if ((object.ReferenceEquals(this.DataVooField, value) != true)) {
                    this.DataVooField = value;
                    this.RaisePropertyChanged("DataVoo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Origem {
            get {
                return this.OrigemField;
            }
            set {
                if ((object.ReferenceEquals(this.OrigemField, value) != true)) {
                    this.OrigemField = value;
                    this.RaisePropertyChanged("Origem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Destino {
            get {
                return this.DestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinoField, value) != true)) {
                    this.DestinoField = value;
                    this.RaisePropertyChanged("Destino");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tom.org/", ConfigurationName="VooWs.VooWSSoap")]
    public interface VooWSSoap {
        
        // CODEGEN: Generating message contract since element name voo from namespace http://tom.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tom.org/Criar", ReplyAction="*")]
        TOM.Web.VooWs.CriarResponse Criar(TOM.Web.VooWs.CriarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tom.org/Criar", ReplyAction="*")]
        System.Threading.Tasks.Task<TOM.Web.VooWs.CriarResponse> CriarAsync(TOM.Web.VooWs.CriarRequest request);
        
        // CODEGEN: Generating message contract since element name voo from namespace http://tom.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tom.org/Editar", ReplyAction="*")]
        TOM.Web.VooWs.EditarResponse Editar(TOM.Web.VooWs.EditarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tom.org/Editar", ReplyAction="*")]
        System.Threading.Tasks.Task<TOM.Web.VooWs.EditarResponse> EditarAsync(TOM.Web.VooWs.EditarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tom.org/Apagar", ReplyAction="*")]
        void Apagar(int idVoo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tom.org/Apagar", ReplyAction="*")]
        System.Threading.Tasks.Task ApagarAsync(int idVoo);
        
        // CODEGEN: Generating message contract since element name BuscarTodosResult from namespace http://tom.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tom.org/BuscarTodos", ReplyAction="*")]
        TOM.Web.VooWs.BuscarTodosResponse BuscarTodos(TOM.Web.VooWs.BuscarTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tom.org/BuscarTodos", ReplyAction="*")]
        System.Threading.Tasks.Task<TOM.Web.VooWs.BuscarTodosResponse> BuscarTodosAsync(TOM.Web.VooWs.BuscarTodosRequest request);
        
        // CODEGEN: Generating message contract since element name filtro from namespace http://tom.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tom.org/BuscarVoosPorFiltro", ReplyAction="*")]
        TOM.Web.VooWs.BuscarVoosPorFiltroResponse BuscarVoosPorFiltro(TOM.Web.VooWs.BuscarVoosPorFiltroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tom.org/BuscarVoosPorFiltro", ReplyAction="*")]
        System.Threading.Tasks.Task<TOM.Web.VooWs.BuscarVoosPorFiltroResponse> BuscarVoosPorFiltroAsync(TOM.Web.VooWs.BuscarVoosPorFiltroRequest request);
        
        // CODEGEN: Generating message contract since element name BuscarPorIdResult from namespace http://tom.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tom.org/BuscarPorId", ReplyAction="*")]
        TOM.Web.VooWs.BuscarPorIdResponse BuscarPorId(TOM.Web.VooWs.BuscarPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tom.org/BuscarPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<TOM.Web.VooWs.BuscarPorIdResponse> BuscarPorIdAsync(TOM.Web.VooWs.BuscarPorIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CriarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Criar", Namespace="http://tom.org/", Order=0)]
        public TOM.Web.VooWs.CriarRequestBody Body;
        
        public CriarRequest() {
        }
        
        public CriarRequest(TOM.Web.VooWs.CriarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tom.org/")]
    public partial class CriarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TOM.Web.VooWs.Voo voo;
        
        public CriarRequestBody() {
        }
        
        public CriarRequestBody(TOM.Web.VooWs.Voo voo) {
            this.voo = voo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CriarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CriarResponse", Namespace="http://tom.org/", Order=0)]
        public TOM.Web.VooWs.CriarResponseBody Body;
        
        public CriarResponse() {
        }
        
        public CriarResponse(TOM.Web.VooWs.CriarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CriarResponseBody {
        
        public CriarResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Editar", Namespace="http://tom.org/", Order=0)]
        public TOM.Web.VooWs.EditarRequestBody Body;
        
        public EditarRequest() {
        }
        
        public EditarRequest(TOM.Web.VooWs.EditarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tom.org/")]
    public partial class EditarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TOM.Web.VooWs.Voo voo;
        
        public EditarRequestBody() {
        }
        
        public EditarRequestBody(TOM.Web.VooWs.Voo voo) {
            this.voo = voo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditarResponse", Namespace="http://tom.org/", Order=0)]
        public TOM.Web.VooWs.EditarResponseBody Body;
        
        public EditarResponse() {
        }
        
        public EditarResponse(TOM.Web.VooWs.EditarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EditarResponseBody {
        
        public EditarResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarTodosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarTodos", Namespace="http://tom.org/", Order=0)]
        public TOM.Web.VooWs.BuscarTodosRequestBody Body;
        
        public BuscarTodosRequest() {
        }
        
        public BuscarTodosRequest(TOM.Web.VooWs.BuscarTodosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class BuscarTodosRequestBody {
        
        public BuscarTodosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarTodosResponse", Namespace="http://tom.org/", Order=0)]
        public TOM.Web.VooWs.BuscarTodosResponseBody Body;
        
        public BuscarTodosResponse() {
        }
        
        public BuscarTodosResponse(TOM.Web.VooWs.BuscarTodosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tom.org/")]
    public partial class BuscarTodosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TOM.Web.VooWs.Voo[] BuscarTodosResult;
        
        public BuscarTodosResponseBody() {
        }
        
        public BuscarTodosResponseBody(TOM.Web.VooWs.Voo[] BuscarTodosResult) {
            this.BuscarTodosResult = BuscarTodosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarVoosPorFiltroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarVoosPorFiltro", Namespace="http://tom.org/", Order=0)]
        public TOM.Web.VooWs.BuscarVoosPorFiltroRequestBody Body;
        
        public BuscarVoosPorFiltroRequest() {
        }
        
        public BuscarVoosPorFiltroRequest(TOM.Web.VooWs.BuscarVoosPorFiltroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tom.org/")]
    public partial class BuscarVoosPorFiltroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TOM.Web.VooWs.FiltroBuscaVooDTO filtro;
        
        public BuscarVoosPorFiltroRequestBody() {
        }
        
        public BuscarVoosPorFiltroRequestBody(TOM.Web.VooWs.FiltroBuscaVooDTO filtro) {
            this.filtro = filtro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarVoosPorFiltroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarVoosPorFiltroResponse", Namespace="http://tom.org/", Order=0)]
        public TOM.Web.VooWs.BuscarVoosPorFiltroResponseBody Body;
        
        public BuscarVoosPorFiltroResponse() {
        }
        
        public BuscarVoosPorFiltroResponse(TOM.Web.VooWs.BuscarVoosPorFiltroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tom.org/")]
    public partial class BuscarVoosPorFiltroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TOM.Web.VooWs.Voo[] BuscarVoosPorFiltroResult;
        
        public BuscarVoosPorFiltroResponseBody() {
        }
        
        public BuscarVoosPorFiltroResponseBody(TOM.Web.VooWs.Voo[] BuscarVoosPorFiltroResult) {
            this.BuscarVoosPorFiltroResult = BuscarVoosPorFiltroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarPorId", Namespace="http://tom.org/", Order=0)]
        public TOM.Web.VooWs.BuscarPorIdRequestBody Body;
        
        public BuscarPorIdRequest() {
        }
        
        public BuscarPorIdRequest(TOM.Web.VooWs.BuscarPorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tom.org/")]
    public partial class BuscarPorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idVoo;
        
        public BuscarPorIdRequestBody() {
        }
        
        public BuscarPorIdRequestBody(int idVoo) {
            this.idVoo = idVoo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarPorIdResponse", Namespace="http://tom.org/", Order=0)]
        public TOM.Web.VooWs.BuscarPorIdResponseBody Body;
        
        public BuscarPorIdResponse() {
        }
        
        public BuscarPorIdResponse(TOM.Web.VooWs.BuscarPorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tom.org/")]
    public partial class BuscarPorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TOM.Web.VooWs.Voo BuscarPorIdResult;
        
        public BuscarPorIdResponseBody() {
        }
        
        public BuscarPorIdResponseBody(TOM.Web.VooWs.Voo BuscarPorIdResult) {
            this.BuscarPorIdResult = BuscarPorIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VooWSSoapChannel : TOM.Web.VooWs.VooWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VooWSSoapClient : System.ServiceModel.ClientBase<TOM.Web.VooWs.VooWSSoap>, TOM.Web.VooWs.VooWSSoap {
        
        public VooWSSoapClient() {
        }
        
        public VooWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VooWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VooWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VooWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TOM.Web.VooWs.CriarResponse TOM.Web.VooWs.VooWSSoap.Criar(TOM.Web.VooWs.CriarRequest request) {
            return base.Channel.Criar(request);
        }
        
        public void Criar(TOM.Web.VooWs.Voo voo) {
            TOM.Web.VooWs.CriarRequest inValue = new TOM.Web.VooWs.CriarRequest();
            inValue.Body = new TOM.Web.VooWs.CriarRequestBody();
            inValue.Body.voo = voo;
            TOM.Web.VooWs.CriarResponse retVal = ((TOM.Web.VooWs.VooWSSoap)(this)).Criar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TOM.Web.VooWs.CriarResponse> TOM.Web.VooWs.VooWSSoap.CriarAsync(TOM.Web.VooWs.CriarRequest request) {
            return base.Channel.CriarAsync(request);
        }
        
        public System.Threading.Tasks.Task<TOM.Web.VooWs.CriarResponse> CriarAsync(TOM.Web.VooWs.Voo voo) {
            TOM.Web.VooWs.CriarRequest inValue = new TOM.Web.VooWs.CriarRequest();
            inValue.Body = new TOM.Web.VooWs.CriarRequestBody();
            inValue.Body.voo = voo;
            return ((TOM.Web.VooWs.VooWSSoap)(this)).CriarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TOM.Web.VooWs.EditarResponse TOM.Web.VooWs.VooWSSoap.Editar(TOM.Web.VooWs.EditarRequest request) {
            return base.Channel.Editar(request);
        }
        
        public void Editar(TOM.Web.VooWs.Voo voo) {
            TOM.Web.VooWs.EditarRequest inValue = new TOM.Web.VooWs.EditarRequest();
            inValue.Body = new TOM.Web.VooWs.EditarRequestBody();
            inValue.Body.voo = voo;
            TOM.Web.VooWs.EditarResponse retVal = ((TOM.Web.VooWs.VooWSSoap)(this)).Editar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TOM.Web.VooWs.EditarResponse> TOM.Web.VooWs.VooWSSoap.EditarAsync(TOM.Web.VooWs.EditarRequest request) {
            return base.Channel.EditarAsync(request);
        }
        
        public System.Threading.Tasks.Task<TOM.Web.VooWs.EditarResponse> EditarAsync(TOM.Web.VooWs.Voo voo) {
            TOM.Web.VooWs.EditarRequest inValue = new TOM.Web.VooWs.EditarRequest();
            inValue.Body = new TOM.Web.VooWs.EditarRequestBody();
            inValue.Body.voo = voo;
            return ((TOM.Web.VooWs.VooWSSoap)(this)).EditarAsync(inValue);
        }
        
        public void Apagar(int idVoo) {
            base.Channel.Apagar(idVoo);
        }
        
        public System.Threading.Tasks.Task ApagarAsync(int idVoo) {
            return base.Channel.ApagarAsync(idVoo);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TOM.Web.VooWs.BuscarTodosResponse TOM.Web.VooWs.VooWSSoap.BuscarTodos(TOM.Web.VooWs.BuscarTodosRequest request) {
            return base.Channel.BuscarTodos(request);
        }
        
        public TOM.Web.VooWs.Voo[] BuscarTodos() {
            TOM.Web.VooWs.BuscarTodosRequest inValue = new TOM.Web.VooWs.BuscarTodosRequest();
            inValue.Body = new TOM.Web.VooWs.BuscarTodosRequestBody();
            TOM.Web.VooWs.BuscarTodosResponse retVal = ((TOM.Web.VooWs.VooWSSoap)(this)).BuscarTodos(inValue);
            return retVal.Body.BuscarTodosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TOM.Web.VooWs.BuscarTodosResponse> TOM.Web.VooWs.VooWSSoap.BuscarTodosAsync(TOM.Web.VooWs.BuscarTodosRequest request) {
            return base.Channel.BuscarTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<TOM.Web.VooWs.BuscarTodosResponse> BuscarTodosAsync() {
            TOM.Web.VooWs.BuscarTodosRequest inValue = new TOM.Web.VooWs.BuscarTodosRequest();
            inValue.Body = new TOM.Web.VooWs.BuscarTodosRequestBody();
            return ((TOM.Web.VooWs.VooWSSoap)(this)).BuscarTodosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TOM.Web.VooWs.BuscarVoosPorFiltroResponse TOM.Web.VooWs.VooWSSoap.BuscarVoosPorFiltro(TOM.Web.VooWs.BuscarVoosPorFiltroRequest request) {
            return base.Channel.BuscarVoosPorFiltro(request);
        }
        
        public TOM.Web.VooWs.Voo[] BuscarVoosPorFiltro(TOM.Web.VooWs.FiltroBuscaVooDTO filtro) {
            TOM.Web.VooWs.BuscarVoosPorFiltroRequest inValue = new TOM.Web.VooWs.BuscarVoosPorFiltroRequest();
            inValue.Body = new TOM.Web.VooWs.BuscarVoosPorFiltroRequestBody();
            inValue.Body.filtro = filtro;
            TOM.Web.VooWs.BuscarVoosPorFiltroResponse retVal = ((TOM.Web.VooWs.VooWSSoap)(this)).BuscarVoosPorFiltro(inValue);
            return retVal.Body.BuscarVoosPorFiltroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TOM.Web.VooWs.BuscarVoosPorFiltroResponse> TOM.Web.VooWs.VooWSSoap.BuscarVoosPorFiltroAsync(TOM.Web.VooWs.BuscarVoosPorFiltroRequest request) {
            return base.Channel.BuscarVoosPorFiltroAsync(request);
        }
        
        public System.Threading.Tasks.Task<TOM.Web.VooWs.BuscarVoosPorFiltroResponse> BuscarVoosPorFiltroAsync(TOM.Web.VooWs.FiltroBuscaVooDTO filtro) {
            TOM.Web.VooWs.BuscarVoosPorFiltroRequest inValue = new TOM.Web.VooWs.BuscarVoosPorFiltroRequest();
            inValue.Body = new TOM.Web.VooWs.BuscarVoosPorFiltroRequestBody();
            inValue.Body.filtro = filtro;
            return ((TOM.Web.VooWs.VooWSSoap)(this)).BuscarVoosPorFiltroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TOM.Web.VooWs.BuscarPorIdResponse TOM.Web.VooWs.VooWSSoap.BuscarPorId(TOM.Web.VooWs.BuscarPorIdRequest request) {
            return base.Channel.BuscarPorId(request);
        }
        
        public TOM.Web.VooWs.Voo BuscarPorId(int idVoo) {
            TOM.Web.VooWs.BuscarPorIdRequest inValue = new TOM.Web.VooWs.BuscarPorIdRequest();
            inValue.Body = new TOM.Web.VooWs.BuscarPorIdRequestBody();
            inValue.Body.idVoo = idVoo;
            TOM.Web.VooWs.BuscarPorIdResponse retVal = ((TOM.Web.VooWs.VooWSSoap)(this)).BuscarPorId(inValue);
            return retVal.Body.BuscarPorIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TOM.Web.VooWs.BuscarPorIdResponse> TOM.Web.VooWs.VooWSSoap.BuscarPorIdAsync(TOM.Web.VooWs.BuscarPorIdRequest request) {
            return base.Channel.BuscarPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TOM.Web.VooWs.BuscarPorIdResponse> BuscarPorIdAsync(int idVoo) {
            TOM.Web.VooWs.BuscarPorIdRequest inValue = new TOM.Web.VooWs.BuscarPorIdRequest();
            inValue.Body = new TOM.Web.VooWs.BuscarPorIdRequestBody();
            inValue.Body.idVoo = idVoo;
            return ((TOM.Web.VooWs.VooWSSoap)(this)).BuscarPorIdAsync(inValue);
        }
    }
}
